# Generated by Django 5.2.7 on 2025-11-11 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pedidodetalle',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ventadetalle',
            options={'managed': True},
        ),
    ]
