# Generated by Django 5.2.8 on 2025-11-08 22:42

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35, unique=True)),
            ],
            options={
                'db_table': 'rol',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsuarioGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioUserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(db_column='contrasena', max_length=255)),
                ('username', models.CharField(db_column='documento', help_text='Documento de identidad.', max_length=150, unique=True)),
                ('first_name', models.CharField(db_column='nombres', max_length=50)),
                ('last_name', models.CharField(db_column='apellidos', max_length=50)),
                ('email', models.EmailField(db_column='correo', max_length=60, unique=True)),
                ('date_joined', models.DateTimeField(db_column='fecha_creacion', default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, db_column='ultimo_login', null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(default='activo', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='usuario_set', related_query_name='usuario', through='users.UsuarioGroups', to='auth.group', verbose_name='groups')),
                ('rol', models.ForeignKey(db_column='rol_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.rol')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='usuario_set', related_query_name='usuario', through='users.UsuarioUserPermissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
