"""
Django settings for la_playita_project project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^(rk4r&@kj)93sjzv49k-^a+ua-&cyp!mu499jg5aj0!j2z3*i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    # Local apps (users needs template priority over admin)
    'users.apps.UsersConfig',
    'core.apps.CoreConfig',
    'django.contrib.admin',
    'inventory.apps.InventoryConfig',
    'pos.apps.PosConfig',
    'pqrs.apps.PqrsConfig',
    'suppliers.apps.SuppliersConfig',
    'clients.apps.ClientsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'la_playita_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'users.context_processors.role_flags',
            ],
            'builtins': [
                'users.templatetags.auth_extras',
            ],
        },
    },
]

WSGI_APPLICATION = 'la_playita_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# C:\laplayita\la_playita_project\la_playita_project\settings.py

DATABASES = {
    'default': {
        # ¡CAMBIO CLAVE! Usamos PyMySQL en lugar de mysqlclient.
        'ENGINE': 'django.db.backends.mysql', 
        'NAME': 'laplayita',       # <--- Nombre de tu DB
        'USER': 'root',            # <--- Tu usuario de DB
        'PASSWORD': '12345678', # <--- ¡IMPORTANTE: Cámbialo por tu contraseña!
        'HOST': 'localhost',       # O la IP de tu servidor
        'PORT': '3309',            
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = '/'
# URL de login usada por @login_required y redirecciones automáticas.
# Apunta a la vista de login dentro de la app 'users'.
LOGIN_URL = '/users/login/'

# Session Duration Settings
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Expire session when browser is closed
SESSION_COOKIE_AGE = 1800                 # Expire session after 30 minutes of inactivity (30 * 60)
SESSION_SAVE_EVERY_REQUEST = True       # Reset inactivity timer on each request

# Cambiar el motor de sesiones para no usar la base de datos.
# Esto es necesario porque las migraciones están deshabilitadas.
# Las sesiones se guardarán en cookies firmadas.
SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'users.Usuario'

# =====================================================
# Desactivar migraciones globalmente
# =====================================================
# Esta aplicación utiliza una base de datos existente (volcado SQL) sin 
# gestión de migraciones de Django. Todos los modelos tienen Meta.managed=False
# o corresponden a tablas pre-existentes. Por lo tanto, desactivamos las 
# migraciones completamente para evitar que Django intente crear/modificar
# tablas o aplicar cambios de esquema que podrían entrar en conflicto con
# la estructura existente.

class DisableMigrations(dict):
    """
    Disable all migrations for all apps.
    Every app will use its existing tables without migrations.
    """
    def __contains__(self, item):
        return True

    def __getitem__(self, item):
        return None


MIGRATION_MODULES = DisableMigrations()
# ----------------------------------------------
# Configuración de Correo Electrónico
# ----------------------------------------------

# ¡ACCIÓN REQUERIDA! Para que el envío de correos funcione, debes configurar un servidor SMTP.
# A continuación se muestra un ejemplo usando Gmail.

# 1. CAMBIA EL BACKEND:
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' # Comenta o elimina esta línea
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# 2. CONFIGURA LOS DETALLES DE TU SERVIDOR SMTP (ejemplo para Gmail):
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# 3. INGRESA TUS CREDENCIALES (¡No las guardes directamente en el código en producción!):
EMAIL_HOST_USER = 'soporte.laplayita@gmail.com'
EMAIL_HOST_PASSWORD = 'jvcizyxemizesuwr'

# NOTA IMPORTANTE SOBRE GMAIL:
# Necesitarás generar una "Contraseña de Aplicación" para tu cuenta de Google.
# No uses tu contraseña normal. Lee cómo hacerlo aquí:
# https://support.google.com/accounts/answer/185833