# Generated by Django 5.2.7 on 2025-10-12 20:14

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=50)),
                ('cantidad_disponible', models.PositiveIntegerField()),
                ('costo_unitario_lote', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_caducidad', models.DateField()),
                ('fecha_entrada', models.DateTimeField()),
            ],
            options={
                'db_table': 'lote',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('tipo_movimiento', models.CharField(max_length=20)),
                ('fecha_movimiento', models.DateTimeField()),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('venta_id', models.IntegerField(blank=True, null=True)),
                ('reabastecimiento_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movimiento_inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pqrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pqrs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PqrsHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('descripcion_cambio', models.TextField(blank=True, null=True)),
                ('fecha_cambio', models.DateTimeField()),
            ],
            options={
                'db_table': 'pqrs_historial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('stock_minimo', models.IntegerField()),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reabastecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('forma_pago', models.CharField(blank=True, max_length=25, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reabastecimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReabastecimientoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'reabastecimiento_detalle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField()),
                ('metodo_pago', models.CharField(max_length=25)),
                ('canal_venta', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'venta_detalle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('username', models.CharField(db_column='documento', help_text='Documento de identidad.', max_length=150, unique=True)),
                ('first_name', models.CharField(db_column='nombres', max_length=50)),
                ('last_name', models.CharField(db_column='apellidos', max_length=50)),
                ('email', models.EmailField(db_column='correo', max_length=60, unique=True)),
                ('date_joined', models.DateTimeField(db_column='fecha_creacion', default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, db_column='ultimo_login', null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(default='activo', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
