# Generated by Django 5.2.7 on 2025-10-15 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_create_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': True},
        ),
    ]
