# Generated by Django 5.2.7 on 2025-10-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_producto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_actual',
            field=models.PositiveIntegerField(default=0, help_text='Calculado automáticamente a partir de los lotes.'),
        ),
    ]
