# Generated by Django 5.2.7 on 2025-10-18 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20251014_2210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lote',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='reabastecimiento',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='reabastecimientodetalle',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.categoria'),
        ),
    ]
