# Generated by Django 5.2.7 on 2025-10-18 16:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_lote_options_alter_proveedor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.producto'),
        ),
        migrations.AddField(
            model_name='lote',
            name='reabastecimiento_detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.reabastecimientodetalle'),
        ),
        migrations.AddField(
            model_name='reabastecimiento',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.proveedor'),
        ),
        migrations.AddField(
            model_name='reabastecimientodetalle',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.producto'),
        ),
        migrations.AddField(
            model_name='reabastecimientodetalle',
            name='reabastecimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.reabastecimiento'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='fecha_entrada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='lote',
            unique_together={('producto', 'numero_lote')},
        ),
    ]
