# Generated by Django 5.2.7 on 2025-10-23 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_lote_producto_lote_reabastecimiento_detalle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reabastecimientodetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.producto'),
        ),
    ]
