# Generated by Django 5.2.7 on 2025-10-24 19:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_reabastecimientodetalle_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reabastecimiento',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
