# Generated by Django 5.2.7 on 2025-10-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_reabastecimiento_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reabastecimiento',
            name='estado',
            field=models.CharField(blank=True, choices=[('solicitado', 'Solicitado'), ('enviado', 'Enviado'), ('recibido', 'Recibido'), ('cancelado', 'Cancelado')], default='solicitado', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reabastecimiento',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('transferencia', 'Transferencia Bancaria'), ('efectivo', 'Efectivo'), ('cheque', 'Cheque'), ('pse', 'PSE'), ('tarjeta_credito', 'Tarjeta de Crédito'), ('consignacion', 'Consignación Bancaria')], max_length=25, null=True),
        ),
    ]
