# Generated by Django 5.2.7 on 2025-10-26 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_reabastecimientodetalle_fecha_caducidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reabastecimiento',
            name='estado',
            field=models.CharField(blank=True, choices=[('solicitado', 'Solicitado'), ('recibido', 'Recibido'), ('cancelado', 'Cancelado')], default='solicitado', max_length=20, null=True),
        ),
    ]
