# Generated by Django 5.2.7 on 2025-10-28 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_reabastecimiento_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'managed': True},
        ),
    ]
