# Generated by Django 5.2.7 on 2025-10-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_venta_cliente_venta_total_venta_venta_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='costo_promedio',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo promedio ponderado, calculado automáticamente a partir de los lotes.', max_digits=12),
        ),
    ]
