# Generated by Django 5.2.7 on 2025-11-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_producto_costo_promedio'),
    ]

    operations = [
        migrations.AddField(
            model_name='reabastecimientodetalle',
            name='cantidad_recibida',
            field=models.IntegerField(default=0),
        ),
    ]
